NUM_GPUS: 2
MODEL: "baseline"
DATALOADER:
  WORKERS: 4
  SHUFFLE: True
  PIX2PIX: True
  RGB_PATH: "/SPACE/DATA/KITTI_Data/KITTI_raw_data/kitti/2011_09_26"
  SEGMENTED_PATH: "/home/fatih/Inputs/LidarData"
CAMERA_GENERATOR:
  BASE_LR: 0.0002
  STEP_SIZE: 100
  STEP_GAMMA: 0.5
  PIXEL_LAMBDA: 100
CAMERA_DISCRIMINATOR:
  BASE_LR: 0.00002
  STEP_SIZE: 20
  STEP_GAMMA: 0.5
TRAIN:
  BETA1: 0.5
  BETA2: 0.999
  LAMBDA_GP: 10
  BATCH_SIZE: 8
  SAVE_AT: 5
  START_EPOCH: 0
  MAX_EPOCH: 100
  LOAD_WEIGHTS: ""
  SAVE_WEIGHTS: "/home/fatih/my_git/sensorgan/outputs/baseline_models/"
  DISCRIMINATOR_CRITERION_REDUCTION: "mean"
  CYCLE_LOSS_REDUCTION: "mean"
  EXAMPLE_SAVE_PATH: "/home/fatih/my_git/sensorgan/outputs/baseline_examples/"
  GRAPH_SAVE_PATH: "/home/fatih/my_git/sensorgan/outputs/baseline_graphs/"
OUTPUT_DIR: ""