NUM_GPUS: 2
DATALOADER:
  WORKERS: 2
  SHUFFLE: True
  LIDAR_DATA_PATH: "/home/fatih/Inputs/LidarData"
  CAMERA_DATA_PATH: "/home/fatih/Inputs/CameraData"
LIDAR_GENERATOR:
  BASE_LR: 0.0001
LIDAR_DISCRIMINATOR:
  BASE_LR: 0.0001
CAMERA_GENERATOR:
  BASE_LR: 0.0001
CAMERA_DISCRIMINATOR:
  BASE_LR: 0.00001
TRAIN:
  BATCH_SIZE: 8
  START_EPOCH: 0
  MAX_EPOCH: 1000
  LOAD_WEIGHTS: ""
  SAVE_WEIGHTS: ""
  DISCRIMINATOR_CRITERION_REDUCTION: "mean"
  CYCLE_LOSS_REDUCTION: "mean"
  EXAMPLE_SAVE_PATH: "/home/fatih/my_git/sensorgan/outputs/examples/"
  GRAPH_SAVE_PATH: "/home/fatih/my_git/sensorgan/outputs/graphs/"
OUTPUT_DIR: ""